[project]
name = "nodexlwebapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.128.0",
    "pdfplumber>=0.11.8",
    "pyinstaller==6.19.0",
    "python-multipart>=0.0.22",
    "rapidfuzz>=3.14.3",
    "slowapi>=0.1.9",
    "sqlalchemy>=2.0.0",
    "uvicorn>=0.40.0",
]
